import { 
  FoodBatch, 
  DemandForecastRecord, 
  NGOPartner, 
  DonationRequest, 
  DeliveryRoute, 
  AppSettings,
  VirtualIoTSensorData 
} from '../types';

export const DEFAULT_SETTINGS: AppSettings = {
  kitchenName: 'Smart College Canteen',
  kitchenAddress: 'Near Kanaka Durga Varadhi, MG Road, Vijayawada, AP 520010',
  city: 'Vijayawada',
  contactPerson: 'K. Ramesh Babu (Canteen Manager)',
  phoneNumber: '+91 98480 23456',
  kitchenCapacity: 500,
  defaultRedistributionDeadlineHours: 4,
  safeTempThreshold: 8,
  avgMealPortionKg: 0.25,
  costPerKgRupees: 200,
  carbonFactorKgCO2PerKg: 2.5,
  defaultVehicleSpeedKmh: 20,
  emailAlerts: true,
  smsAlerts: true,
  autoNgoBroadcast: true
};

export const INITIAL_NGOS: NGOPartner[] = [
  {
    id: 'ngo-1',
    name: 'Hope Food Bank',
    area: 'Benz Circle, Vijayawada',
    address: 'Plot 42, Near Joyalukkas, Benz Circle, Vijayawada, AP 520010',
    distanceKm: 3.2,
    capacityKg: 25,
    currentAvailability: 'Available',
    acceptsCategories: ['Cooked Food', 'Packaged Food'],
    operatingHours: '08:00 AM - 10:30 PM',
    phone: '+91 98491 11223',
    contactPerson: 'Smt. Lakshmi Devi',
    rating: 4.9,
    hasRefrigeration: true
  },
  {
    id: 'ngo-2',
    name: 'Seva Shelter Home',
    area: 'Patamata, Vijayawada',
    address: 'Opp. High School Ground, Patamata, Vijayawada, AP 520014',
    distanceKm: 4.5,
    capacityKg: 15,
    currentAvailability: 'Available',
    acceptsCategories: ['Cooked Food'],
    operatingHours: '09:00 AM - 09:00 PM',
    phone: '+91 98492 33445',
    contactPerson: 'Sri P. Venkat Rao',
    rating: 4.7,
    hasRefrigeration: false
  },
  {
    id: 'ngo-3',
    name: 'Helping Hands Foundation',
    area: 'Moghalrajpuram, Vijayawada',
    address: 'Road No. 3, Beside Siddhartha College, Moghalrajpuram, Vijayawada, AP 520010',
    distanceKm: 5.1,
    capacityKg: 40,
    currentAvailability: 'Available',
    acceptsCategories: ['Cooked Food', 'Raw Material', 'Packaged Food'],
    operatingHours: '24 Hours Open',
    phone: '+91 98493 55667',
    contactPerson: 'Dr. Anita Sharma',
    rating: 4.8,
    hasRefrigeration: true
  },
  {
    id: 'ngo-4',
    name: 'Community Kitchen Network',
    area: 'Auto Nagar, Vijayawada',
    address: 'Industrial Estate Gate 2, Auto Nagar, Vijayawada, AP 520007',
    distanceKm: 7.8,
    capacityKg: 60,
    currentAvailability: 'Busy',
    acceptsCategories: ['Cooked Food', 'Raw Material'],
    operatingHours: '06:00 AM - 08:00 PM',
    phone: '+91 98494 77889',
    contactPerson: 'Sri M. Murali Krishna',
    rating: 4.6,
    hasRefrigeration: true
  }
];

export const INITIAL_BATCHES: FoodBatch[] = [
  {
    id: 'BATCH-2026-0924-01',
    foodItem: 'Vegetable Rice & Sambar',
    category: 'Rice',
    foodType: 'Cooked Food',
    mealsPrepared: 310,
    mealsServed: 292,
    preparedKg: 77.5,
    servedKg: 63.5,
    remainingKg: 14.0,
    remainingMeals: 18,
    prepDateTime: '2026-09-24T12:30:00',
    deadlineDateTime: '2026-09-25T18:30:00',
    storageCondition: 'Proper',
    packagingStatus: 'Intact',
    appearance: 'Normal',
    notes: 'Hot insulated thermal storage container in dining block. Prepared for lunch service.',
    qualityScore: 100,
    qualityStatus: 'Safe for Human Review',
    donationStatus: 'Delivered',
    matchedNgoId: 'ngo-1',
    assignedDriver: 'Suresh Kumar (Auto AP 16 TX 4920)',
    deliveryProofUrl: 'https://images.unsplash.com/photo-1593113598332-cd288d649433?auto=format&fit=crop&w=600&q=80'
  },
  {
    id: 'BATCH-2026-0924-02',
    foodItem: 'Dal Tadka & Steamed Rice',
    category: 'Curry',
    foodType: 'Cooked Food',
    mealsPrepared: 280,
    mealsServed: 255,
    preparedKg: 70.0,
    servedKg: 61.5,
    remainingKg: 8.5,
    remainingMeals: 25,
    prepDateTime: '2026-09-26T13:00:00',
    deadlineDateTime: '2026-09-26T22:00:00',
    storageCondition: 'Proper',
    packagingStatus: 'Intact',
    appearance: 'Normal',
    notes: 'Packed in food-grade stainless containers. Suitable for evening feeding.',
    qualityScore: 90,
    qualityStatus: 'Safe for Human Review',
    donationStatus: 'Surplus Detected',
    matchedNgoId: undefined
  },
  {
    id: 'BATCH-2026-0924-03',
    foodItem: 'Mixed Sprouts & Idli Batter',
    category: 'Breakfast',
    foodType: 'Raw Material',
    mealsPrepared: 150,
    mealsServed: 130,
    preparedKg: 25.0,
    servedKg: 20.0,
    remainingKg: 5.0,
    remainingMeals: 20,
    prepDateTime: '2026-09-26T07:00:00',
    deadlineDateTime: '2026-09-27T02:00:00',
    storageCondition: 'Proper',
    packagingStatus: 'Intact',
    appearance: 'Normal',
    notes: 'Chilled in cold storage pantry at 4°C.',
    qualityScore: 95,
    qualityStatus: 'Safe for Human Review',
    donationStatus: 'Offered',
    matchedNgoId: 'ngo-3'
  },
  {
    id: 'BATCH-2026-0923-01',
    foodItem: 'Veg Biryani & Mirchi Ka Salan',
    category: 'Rice',
    foodType: 'Cooked Food',
    mealsPrepared: 350,
    mealsServed: 330,
    preparedKg: 87.5,
    servedKg: 82.5,
    remainingKg: 5.0,
    remainingMeals: 20,
    prepDateTime: '2026-09-23T12:45:00',
    deadlineDateTime: '2026-09-23T16:45:00',
    storageCondition: 'Proper',
    packagingStatus: 'Intact',
    appearance: 'Normal',
    qualityScore: 94,
    qualityStatus: 'Safe for Human Review',
    donationStatus: 'Delivered',
    matchedNgoId: 'ngo-2'
  },
  {
    id: 'BATCH-2026-0922-01',
    foodItem: 'Chapati & Chana Masala',
    category: 'Curry',
    foodType: 'Cooked Food',
    mealsPrepared: 290,
    mealsServed: 278,
    preparedKg: 65.0,
    servedKg: 62.0,
    remainingKg: 3.0,
    remainingMeals: 12,
    prepDateTime: '2026-09-22T19:30:00',
    deadlineDateTime: '2026-09-22T23:30:00',
    storageCondition: 'Proper',
    packagingStatus: 'Intact',
    appearance: 'Normal',
    qualityScore: 88,
    qualityStatus: 'Safe for Human Review',
    donationStatus: 'Delivered',
    matchedNgoId: 'ngo-1'
  },
  {
    id: 'BATCH-2026-0921-01',
    foodItem: 'Tomato Rice & Boondi Raita',
    category: 'Rice',
    foodType: 'Cooked Food',
    mealsPrepared: 320,
    mealsServed: 288,
    preparedKg: 80.0,
    servedKg: 72.0,
    remainingKg: 8.0,
    remainingMeals: 32,
    prepDateTime: '2026-09-21T12:30:00',
    deadlineDateTime: '2026-09-21T16:30:00',
    storageCondition: 'Improper',
    packagingStatus: 'Damaged',
    appearance: 'Suspicious',
    qualityScore: 42,
    qualityStatus: 'Do Not Redistribute',
    donationStatus: 'Do Not Redistribute',
    notes: 'Exposed to room temperature for over 5 hours without lid. Marked unsafe.'
  }
];

export const INITIAL_FORECASTS: DemandForecastRecord[] = [
  {
    id: 'FC-2026-0924-L',
    date: '2026-09-24',
    mealType: 'Lunch',
    foodItem: 'Vegetable Rice',
    category: 'Rice',
    expectedAttendance: 320,
    dayOfWeek: 'Thursday',
    isHolidayOrEvent: false,
    isSpecialMenu: false,
    prevDayDemand: 295,
    avg7DayDemand: 295,
    predictedDemand: 295,
    recommendedPreparation: 310,
    actualMealsServed: 292,
    confidenceScore: 88,
    overproductionRisk: 'Low',
    aiRecommendation: 'Prepare approximately 310 meals. Avoid preparing above 325 meals to reduce overproduction risk.',
    accuracy: 98.9,
    status: 'Completed'
  },
  {
    id: 'FC-2026-0925-B',
    date: '2026-09-25',
    mealType: 'Breakfast',
    foodItem: 'Upma & Coconut Chutney',
    category: 'Breakfast',
    expectedAttendance: 260,
    dayOfWeek: 'Friday',
    isHolidayOrEvent: false,
    isSpecialMenu: false,
    prevDayDemand: 245,
    avg7DayDemand: 240,
    predictedDemand: 239,
    recommendedPreparation: 251,
    actualMealsServed: undefined,
    confidenceScore: 91,
    overproductionRisk: 'Low',
    aiRecommendation: 'Prepare approximately 250 meals. High stability on Friday mornings.',
    status: 'Pending Actuals'
  },
  {
    id: 'FC-2026-0925-L',
    date: '2026-09-25',
    mealType: 'Lunch',
    foodItem: 'Sambar Rice & Aloo Fry',
    category: 'Rice',
    expectedAttendance: 340,
    dayOfWeek: 'Friday',
    isHolidayOrEvent: false,
    isSpecialMenu: true,
    prevDayDemand: 292,
    avg7DayDemand: 298,
    predictedDemand: 328,
    recommendedPreparation: 344,
    actualMealsServed: undefined,
    confidenceScore: 86,
    overproductionRisk: 'Medium',
    aiRecommendation: 'Special menu boost (+5%) applied. Recommended 344 meals.',
    status: 'Pending Actuals'
  },
  {
    id: 'FC-2026-0923-L',
    date: '2026-09-23',
    mealType: 'Lunch',
    foodItem: 'Veg Biryani',
    category: 'Rice',
    expectedAttendance: 355,
    dayOfWeek: 'Wednesday',
    isHolidayOrEvent: false,
    isSpecialMenu: true,
    prevDayDemand: 280,
    avg7DayDemand: 290,
    predictedDemand: 343,
    recommendedPreparation: 360,
    actualMealsServed: 330,
    confidenceScore: 89,
    overproductionRisk: 'Medium',
    aiRecommendation: 'Mid-week special menu biryani prediction.',
    accuracy: 96.2,
    status: 'Completed'
  },
  {
    id: 'FC-2026-0922-D',
    date: '2026-09-22',
    mealType: 'Dinner',
    foodItem: 'Chapati & Curry',
    category: 'Curry',
    expectedAttendance: 300,
    dayOfWeek: 'Tuesday',
    isHolidayOrEvent: false,
    isSpecialMenu: false,
    prevDayDemand: 275,
    avg7DayDemand: 274,
    predictedDemand: 276,
    recommendedPreparation: 290,
    actualMealsServed: 278,
    confidenceScore: 92,
    overproductionRisk: 'Low',
    aiRecommendation: 'Stable Tuesday hostel dinner attendance.',
    accuracy: 99.2,
    status: 'Completed'
  }
];

export const INITIAL_IOT_MAP: Map<string, VirtualIoTSensorData> = new Map([
  [
    'BATCH-2026-0924-01',
    {
      batchId: 'BATCH-2026-0924-01',
      temperature: 5.2,
      humidity: 55.0,
      containerWeight: 14.0,
      storageDurationHours: 2.5,
      hoursRemaining: 3.5,
      deviceStatus: 'Online',
      lastUpdated: '2026-09-26T14:15:00',
      alertLevel: 'green',
      alertMessage: 'Optimal Storage Condition (Safe temperature maintained at 5.2°C)',
      readingsHistory: [
        { timestamp: '12:30', temp: 5.0, humidity: 54, weight: 14.2, status: 'Normal' },
        { timestamp: '13:00', temp: 5.1, humidity: 55, weight: 14.1, status: 'Normal' },
        { timestamp: '13:30', temp: 5.3, humidity: 56, weight: 14.0, status: 'Normal' },
        { timestamp: '14:00', temp: 5.2, humidity: 55, weight: 14.0, status: 'Normal' },
        { timestamp: '14:15', temp: 5.2, humidity: 55, weight: 14.0, status: 'Normal' },
      ]
    }
  ],
  [
    'BATCH-2026-0924-02',
    {
      batchId: 'BATCH-2026-0924-02',
      temperature: 6.0,
      humidity: 58.0,
      containerWeight: 8.5,
      storageDurationHours: 1.5,
      hoursRemaining: 4.5,
      deviceStatus: 'Online',
      lastUpdated: '2026-09-26T14:30:00',
      alertLevel: 'green',
      alertMessage: 'Optimal Storage Condition (Safe temperature maintained at 6.0°C)',
      readingsHistory: [
        { timestamp: '13:00', temp: 5.8, humidity: 57, weight: 8.5, status: 'Normal' },
        { timestamp: '13:30', temp: 5.9, humidity: 58, weight: 8.5, status: 'Normal' },
        { timestamp: '14:00', temp: 6.0, humidity: 58, weight: 8.5, status: 'Normal' },
      ]
    }
  ],
  [
    'BATCH-2026-0924-03',
    {
      batchId: 'BATCH-2026-0924-03',
      temperature: 4.2,
      humidity: 62.0,
      containerWeight: 5.0,
      storageDurationHours: 3.0,
      hoursRemaining: 5.0,
      deviceStatus: 'Online',
      lastUpdated: '2026-09-26T14:40:00',
      alertLevel: 'green',
      alertMessage: 'Cold Storage Safe (Chilled at 4.2°C)',
      readingsHistory: [
        { timestamp: '12:00', temp: 4.0, humidity: 60, weight: 5.0, status: 'Normal' },
        { timestamp: '13:00', temp: 4.1, humidity: 61, weight: 5.0, status: 'Normal' },
        { timestamp: '14:00', temp: 4.2, humidity: 62, weight: 5.0, status: 'Normal' },
      ]
    }
  ]
]);

export const INITIAL_IOT_DATA: VirtualIoTSensorData =
  INITIAL_IOT_MAP.values().next().value!;

export const INITIAL_DONATION_REQUESTS: DonationRequest[] = [
  {
    id: 'REQ-2026-001',
    batchId: 'BATCH-2026-0924-01',
    ngoId: 'ngo-1',
    ngoName: 'Hope Food Bank',
    foodItem: 'Vegetable Rice & Sambar',
    quantityKg: 14.0,
    preparationTime: '2026-09-24T12:30:00',
    deadline: '2026-09-24T17:30:00',
    pickupAddress: 'Smart College Canteen, Near Kanaka Durga Varadhi, MG Road, Vijayawada',
    pickupWindow: '02:30 PM - 03:30 PM',
    qualityStatus: 'Safe for Human Review',
    status: 'Delivered',
    notes: 'Hot thermal containers ready at ground-floor delivery ramp.',
    createdAt: '2026-09-24T13:45:00'
  },
  {
    id: 'REQ-2026-002',
    batchId: 'BATCH-2026-0923-01',
    ngoId: 'ngo-2',
    ngoName: 'Seva Shelter Home',
    foodItem: 'Veg Biryani & Mirchi Ka Salan',
    quantityKg: 5.0,
    preparationTime: '2026-09-23T12:45:00',
    deadline: '2026-09-23T16:45:00',
    pickupAddress: 'Smart College Canteen, MG Road, Vijayawada',
    pickupWindow: '01:30 PM - 02:15 PM',
    qualityStatus: 'Safe for Human Review',
    status: 'Delivered',
    createdAt: '2026-09-23T13:10:00'
  }
];

export const INITIAL_DELIVERY_ROUTES: DeliveryRoute[] = [
  {
    id: 'ROUTE-2026-001',
    donationId: 'REQ-2026-001',
    batchId: 'BATCH-2026-0924-01',
    ngoId: 'ngo-1',
    ngoName: 'Hope Food Bank',
    origin: 'Smart College Canteen, Vijayawada',
    destination: 'Hope Food Bank, Benz Circle, Vijayawada',
    distanceKm: 3.2,
    vehicleType: 'Auto',
    speedKmh: 20,
    travelTimeMinutes: 10,
    handlingTimeMinutes: 10,
    totalTimeMinutes: 20,
    pickupDeadline: '2026-09-24T17:30:00',
    estimatedArrival: '2026-09-24T14:40:00',
    safetyStatus: 'Safe',
    currentStep: 6, // Delivered
    driverName: 'Suresh Kumar',
    driverPhone: '+91 98499 12345',
    proofImage: 'https://images.unsplash.com/photo-1593113598332-cd288d649433?auto=format&fit=crop&w=600&q=80',
    completedAt: '2026-09-24T14:38:00'
  }
];
